(source gnu)
(source melpa)

(depends-on "use-package")
(depends-on "cider")
(depends-on "evil")
(depends-on "evil-leader")
(depends-on "evil-surround")
(depends-on "evil-paredit")
(depends-on "paredit")
(depends-on "clojure-mode")
(depends-on "clj-refactor")
(depends-on "clojure-snippets")
(depends-on "auto-complete")
(depends-on "ac-cider")
(depends-on "solarized-theme")
(depends-on "relative-line-numbers")
(depends-on "projectile" :git "git@github.com:bbatsov/projectile.git" :ref "master")
(depends-on "ag")
(depends-on "grizzl" :git "https://github.com/grizzl/grizzl.git" :ref "master")
(depends-on "inf-mongo" :git "git://github.com/tobiassvn/inf-mongo.git" :ref "master")
(depends-on "robe")
(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
