
(defun set-evil-magit-bindings ()
  ;(evil-set-initial-state 'magit-mode 'motion)
  (defvar magit-mode-map
    (let ((map (copy-keymap evil-motion-state-map)))
      ;(set-keymap-parent map evil-motion-state-map)
      (define-key map (kbd "n") 'magit-goto-next-section)
      (define-key map (kbd "p") 'magit-goto-previous-section)
      (define-key map (kbd "^") 'magit-goto-parent-section)
      (define-key map (kbd "C-n") 'magit-goto-next-sibling-section)
      (define-key map (kbd "C-p") 'magit-goto-previous-sibling-section)
      (define-key map (kbd "TAB") 'magit-toggle-section)
      (define-key map (kbd "<backtab>") 'magit-expand-collapse-section)
      (define-key map (kbd "1") 'magit-show-level-1)
      (define-key map (kbd "2") 'magit-show-level-2)
      (define-key map (kbd "3") 'magit-show-level-3)
      (define-key map (kbd "4") 'magit-show-level-4)
      ;(define-key map (kbd "M-1") 'magit-show-level-1-all)
      ;(define-key map (kbd "M-2") 'magit-show-level-2-all)
      ;(define-key map (kbd "M-3") 'magit-show-level-3-all)
      ;(define-key map (kbd "M-4") 'magit-show-level-4-all)
      ;(define-key map (kbd "M-h") 'magit-show-only-files)
      ;(define-key map (kbd "M-H") 'magit-show-only-files-all)
      ;(define-key map (kbd "M-s") 'magit-show-level-4)
      ;(define-key map (kbd "M-S") 'magit-show-level-4-all)
      ;(define-key map (kbd "g") 'magit-refresh)
      ;(define-key map (kbd "G") 'magit-refresh-all)
      ;(define-key map (kbd "?") 'magit-key-mode-popup-dispatch)
      (define-key map (kbd ":") 'magit-git-command)
      ;(define-key map (kbd "C-x 4 a") 'magit-add-change-log-entry-other-window)
      ;(define-key map (kbd "L") 'magit-add-change-log-entry)
      (define-key map (kbd "RET") 'magit-visit-item)
      ;(define-key map (kbd "C-<return>") 'magit-dired-jump)
      ;(define-key map (kbd "SPC") 'magit-show-item-or-scroll-up)
      ;(define-key map (kbd "DEL") 'magit-show-item-or-scroll-down)
      ;(define-key map (kbd "C-w") 'magit-copy-item-as-kill)
      ;(cond (magit-rigid-key-bindings
      ;       (define-key map (kbd "c") 'magit-commit)
      ;       (define-key map (kbd "m") 'magit-merge)
      ;       (define-key map (kbd "b") 'magit-checkout)
      ;       (define-key map (kbd "M") 'magit-branch-manager)
      ;       (define-key map (kbd "r") 'undefined)
      ;       (define-key map (kbd "f") 'magit-fetch-current)
      ;       (define-key map (kbd "F") 'magit-pull)
      ;       (define-key map (kbd "J") 'magit-apply-mailbox)
      ;       (define-key map (kbd "!") 'magit-git-command-topdir)
      ;       (define-key map (kbd "P") 'magit-push)
      ;       (define-key map (kbd "t") 'magit-tag)
      ;       (define-key map (kbd "l") 'magit-log)
      ;       (define-key map (kbd "o") 'magit-submodule-update)
      ;       (define-key map (kbd "B") 'undefined)
      ;       (define-key map (kbd "z") 'magit-stash))
      ;      (t
      ;       (define-key map (kbd "c") 'magit-key-mode-popup-committing)
      ;       (define-key map (kbd "m") 'magit-key-mode-popup-merging)
      ;       (define-key map (kbd "b") 'magit-key-mode-popup-branching)
      ;       (define-key map (kbd "M") 'magit-key-mode-popup-remoting)
      ;       (define-key map (kbd "r") 'magit-key-mode-popup-rewriting)
      ;       (define-key map (kbd "f") 'magit-key-mode-popup-fetching)
      ;       (define-key map (kbd "F") 'magit-key-mode-popup-pulling)
      ;       (define-key map (kbd "J") 'magit-key-mode-popup-apply-mailbox)
      ;       (define-key map (kbd "!") 'magit-key-mode-popup-running)
      ;       (define-key map (kbd "P") 'magit-key-mode-popup-pushing)
      ;       (define-key map (kbd "t") 'magit-key-mode-popup-tagging)
      ;       (define-key map (kbd "l") 'magit-key-mode-popup-logging)
      ;       (define-key map (kbd "o") 'magit-key-mode-popup-submodule)
      ;       (define-key map (kbd "B") 'magit-key-mode-popup-bisecting)
      ;       (define-key map (kbd "z") 'magit-key-mode-popup-stashing)))
      ;(define-key map (kbd "$") 'magit-process)
      ;(define-key map (kbd "E") 'magit-interactive-rebase)
      ;(define-key map (kbd "R") 'magit-rebase-step)
      ;(define-key map (kbd "e") 'magit-ediff)
      ;(define-key map (kbd "w") 'magit-wazzup)
      ;(define-key map (kbd "y") 'magit-cherry)
      ;(define-key map (kbd "q") 'magit-mode-quit-window)
      ;(define-key map (kbd "x") 'magit-reset-head)
      ;(define-key map (kbd "v") 'magit-revert-item)
      ;(define-key map (kbd "a") 'magit-apply-item)
      ;(define-key map (kbd "A") 'magit-cherry-pick-item)
      ;(define-key map (kbd "d") 'magit-diff-working-tree)
      ;(define-key map (kbd "D") 'magit-diff)
      (define-key map (kbd "[") 'magit-diff-smaller-hunks)
      (define-key map (kbd "]") 'magit-diff-larger-hunks)
      (define-key map (kbd "}") 'magit-diff-default-hunks)
      ;(define-key map ",vl" 'switch-to-magit-process-buffer ) ; does not work because , isn't a prefix key
      ;(define-key map (kbd "h") 'magit-key-mode-popup-diff-options)
      ;(define-key map (kbd "H") 'magit-diff-toggle-refine-hunk)
      ;(define-key map (kbd "S") 'magit-stage-all)
      ;(define-key map (kbd "U") 'magit-unstage-all)
      ;(define-key map (kbd "X") 'magit-reset-working-tree)
      ;(define-key map (kbd "C-c C-c") 'magit-key-mode-popup-dispatch)
      ;(define-key map (kbd "C-c C-e") 'magit-key-mode-popup-dispatch)
      map)
    "BLAKE's EVIL Parent keymap for all keymaps of modes derived from `magit-mode'.") 

  (defvar magit-status-mode-map
    (let ((map (make-sparse-keymap)))
      (set-keymap-parent map magit-mode-map)
      (define-key map (kbd "n") 'say-poo)
      (define-key map (kbd "p") '(lambda () (interactive) (message "WOOOH")))
      map)
    "BLAKE's EVIL Parent keymap for all keymaps of modes derived from `magit-mode'.")

  (defvar magit-commit-mode-map
    (let ((map (make-sparse-keymap)))
      (set-keymap-parent map magit-mode-map)
      (define-key map (kbd "C-c C-b") 'magit-go-backward)
      (define-key map (kbd "C-c C-f") 'magit-go-forward)
      (define-key map (kbd "SPC") 'scroll-up)
      (define-key map (kbd "DEL") 'scroll-down)
      (define-key map (kbd "j") 'magit-jump-to-diffstats)
      map)
    "Keymap for `magit-commit-mode'.")
  
  (defvar magit-status-mode-map
    (let ((map (make-sparse-keymap)))
      (set-keymap-parent map magit-mode-map)
      (define-key map (kbd "s") 'magit-stage-item)
      (define-key map (kbd "u") 'magit-unstage-item)
      (define-key map (kbd "i") 'magit-ignore-item)
      (define-key map (kbd "I") 'magit-ignore-item-locally)
      (define-key map (kbd "j") 'magit-section-jump-map)
      (define-key map (kbd ".") 'magit-mark-item)
      (define-key map (kbd "=") 'magit-diff-with-mark)
      (define-key map (kbd "k") 'magit-discard-item)
      (define-key map (kbd "C") 'magit-commit-add-log)
      map)
    "Keymap for `magit-status-mode'.")

  (defvar magit-log-mode-map
    (let ((map (make-sparse-keymap)))
      (set-keymap-parent map magit-mode-map)
      (define-key map (kbd ".") 'magit-mark-item)
      (define-key map (kbd "=") 'magit-diff-with-mark)
      (define-key map (kbd "e") 'magit-log-show-more-entries)
      (define-key map (kbd "h") 'magit-log-toggle-margin)
      map)
    "Keymap for `magit-log-mode'.")
  
  (defvar magit-cherry-mode-map
    (let ((map (make-sparse-keymap)))
      (set-keymap-parent map magit-mode-map)
      map)
    "Keymap for `magit-cherry-mode'.")
  
  (defvar magit-reflog-mode-map
    (let ((map (make-sparse-keymap)))
      (set-keymap-parent map magit-log-mode-map)
      map)
    "Keymap for `magit-reflog-mode'.")
  
  (defvar magit-diff-mode-map
    (let ((map (make-sparse-keymap)))
      (set-keymap-parent map magit-mode-map)
      (define-key map (kbd "C-c C-b") 'magit-go-backward)
      (define-key map (kbd "C-c C-f") 'magit-go-forward)
      (define-key map (kbd "SPC") 'scroll-up)
      (define-key map (kbd "DEL") 'scroll-down)
      (define-key map (kbd "j") 'magit-jump-to-diffstats)
      map)
    "Keymap for `magit-diff-mode'.")
  
  (defvar magit-wazzup-mode-map
    (let ((map (make-sparse-keymap)))
      (set-keymap-parent map magit-mode-map)
      (define-key map (kbd ".") 'magit-mark-item)
      (define-key map (kbd "=") 'magit-diff-with-mark)
      (define-key map (kbd "i") 'magit-ignore-item)
      map)
    "Keymap for `magit-wazzup-mode'.")
  
  (defvar magit-branch-manager-mode-map
    (let ((map (make-sparse-keymap)))
      (set-keymap-parent map magit-mode-map)
      (define-key map (kbd "c") 'magit-create-branch)
      (define-key map (kbd "a") 'magit-add-remote)
      (define-key map (kbd "r") 'magit-rename-item)
      (define-key map (kbd "k") 'magit-discard-item)
      (define-key map (kbd "T") 'magit-change-what-branch-tracks)
      map)
    "Keymap for `magit-branch-manager-mode'.")
  
  (defvar magit-process-mode-map
    (let ((map (make-sparse-keymap)))
      (set-keymap-parent map magit-mode-map)
      map)
    "Keymap for `magit-process-mode'.")
  
  (defvar magit-section-jump-map
    (let ((map (make-sparse-keymap)))
      (define-key map (kbd "z") 'magit-jump-to-stashes)
      (define-key map (kbd "n") 'magit-jump-to-untracked)
      (define-key map (kbd "u") 'magit-jump-to-unstaged)
      (define-key map (kbd "s") 'magit-jump-to-staged)
      (define-key map (kbd "f") 'magit-jump-to-unpulled)
      (define-key map (kbd "p") 'magit-jump-to-unpushed)
      (define-key map (kbd "r") 'magit-jump-to-pending)
      map)
    "Submap for jumping to sections in `magit-status-mode'.")

  )
